/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingApprovalRouteImport } from './routes/waiting-approval'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
<<<<<<< HEAD
import { Route as EmployeeReportsRouteImport } from './routes/employee/reports'
=======
>>>>>>> janani/main
import { Route as EmployeeProgramsRouteImport } from './routes/employee/programs'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppResearcherRouteImport } from './routes/_app.researcher'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProgramsRouteImport } from './routes/_app.programs'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppEmployeeRouteImport } from './routes/_app.employee'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
<<<<<<< HEAD
=======
import { Route as EmployeeReportsIndexRouteImport } from './routes/employee/reports/index'
import { Route as EmployeeReportsReportIdRouteImport } from './routes/employee/reports/$reportId'
>>>>>>> janani/main
import { Route as AppReportsNewRouteImport } from './routes/_app.reports.new'
import { Route as AppReportsReportIdRouteImport } from './routes/_app.reports.$reportId'

const WaitingApprovalRoute = WaitingApprovalRouteImport.update({
  id: '/waiting-approval',
  path: '/waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
<<<<<<< HEAD
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
=======
>>>>>>> janani/main
const EmployeeProgramsRoute = EmployeeProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppResearcherRoute = AppResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeRoute = AppEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
<<<<<<< HEAD
=======
const EmployeeReportsIndexRoute = EmployeeReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeReportsReportIdRoute = EmployeeReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
>>>>>>> janani/main
const AppReportsNewRoute = AppReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof AppEmployeeRoute
  '/blog': typeof BlogRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/manager': typeof AppManagerRoute
  '/organizations': typeof AppOrganizationsRoute
  '/programs': typeof AppProgramsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/researcher': typeof AppResearcherRoute
  '/users': typeof AppUsersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/programs': typeof EmployeeProgramsRoute
<<<<<<< HEAD
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
=======
  '/employee/': typeof EmployeeIndexRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
  '/employee/reports/$reportId': typeof EmployeeReportsReportIdRoute
  '/employee/reports/': typeof EmployeeReportsIndexRoute
>>>>>>> janani/main
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof AppManagerRoute
  '/organizations': typeof AppOrganizationsRoute
  '/programs': typeof AppProgramsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/researcher': typeof AppResearcherRoute
  '/users': typeof AppUsersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/programs': typeof EmployeeProgramsRoute
<<<<<<< HEAD
  '/employee/reports': typeof EmployeeReportsRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
=======
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
  '/employee/reports/$reportId': typeof EmployeeReportsReportIdRoute
  '/employee/reports': typeof EmployeeReportsIndexRoute
>>>>>>> janani/main
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/employee': typeof AppEmployeeRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/programs': typeof AppProgramsRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/researcher': typeof AppResearcherRoute
  '/_app/users': typeof AppUsersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/programs': typeof EmployeeProgramsRoute
<<<<<<< HEAD
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/reports/new': typeof AppReportsNewRoute
=======
  '/employee/': typeof EmployeeIndexRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/reports/new': typeof AppReportsNewRoute
  '/employee/reports/$reportId': typeof EmployeeReportsReportIdRoute
  '/employee/reports/': typeof EmployeeReportsIndexRoute
>>>>>>> janani/main
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/blog'
    | '/home'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/admin'
    | '/audit-logs'
    | '/manager'
    | '/organizations'
    | '/programs'
    | '/reports'
    | '/researcher'
    | '/users'
    | '/employee/profile'
    | '/employee/programs'
<<<<<<< HEAD
    | '/employee/reports'
    | '/employee/'
    | '/reports/$reportId'
    | '/reports/new'
=======
    | '/employee/'
    | '/reports/$reportId'
    | '/reports/new'
    | '/employee/reports/$reportId'
    | '/employee/reports/'
>>>>>>> janani/main
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/home'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/admin'
    | '/audit-logs'
    | '/employee'
    | '/manager'
    | '/organizations'
    | '/programs'
    | '/reports'
    | '/researcher'
    | '/users'
    | '/employee/profile'
    | '/employee/programs'
<<<<<<< HEAD
    | '/employee/reports'
    | '/reports/$reportId'
    | '/reports/new'
=======
    | '/reports/$reportId'
    | '/reports/new'
    | '/employee/reports/$reportId'
    | '/employee/reports'
>>>>>>> janani/main
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/_app'
    | '/blog'
    | '/home'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/_app/admin'
    | '/_app/audit-logs'
    | '/_app/employee'
    | '/_app/manager'
    | '/_app/organizations'
    | '/_app/programs'
    | '/_app/reports'
    | '/_app/researcher'
    | '/_app/users'
    | '/employee/profile'
    | '/employee/programs'
<<<<<<< HEAD
    | '/employee/reports'
    | '/employee/'
    | '/_app/reports/$reportId'
    | '/_app/reports/new'
=======
    | '/employee/'
    | '/_app/reports/$reportId'
    | '/_app/reports/new'
    | '/employee/reports/$reportId'
    | '/employee/reports/'
>>>>>>> janani/main
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WaitingApprovalRoute: typeof WaitingApprovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-approval': {
      id: '/waiting-approval'
      path: '/waiting-approval'
      fullPath: '/waiting-approval'
      preLoaderRoute: typeof WaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
<<<<<<< HEAD
    '/employee/reports': {
      id: '/employee/reports'
      path: '/reports'
      fullPath: '/employee/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
=======
>>>>>>> janani/main
    '/employee/programs': {
      id: '/employee/programs'
      path: '/programs'
      fullPath: '/employee/programs'
      preLoaderRoute: typeof EmployeeProgramsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/researcher': {
      id: '/_app/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof AppResearcherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee': {
      id: '/_app/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AppEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
<<<<<<< HEAD
=======
    '/employee/reports/': {
      id: '/employee/reports/'
      path: '/reports'
      fullPath: '/employee/reports/'
      preLoaderRoute: typeof EmployeeReportsIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/reports/$reportId': {
      id: '/employee/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/employee/reports/$reportId'
      preLoaderRoute: typeof EmployeeReportsReportIdRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
>>>>>>> janani/main
    '/_app/reports/new': {
      id: '/_app/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AppReportsNewRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface EmployeeRouteRouteChildren {
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeProgramsRoute: typeof EmployeeProgramsRoute
<<<<<<< HEAD
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
=======
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeReportsReportIdRoute: typeof EmployeeReportsReportIdRoute
  EmployeeReportsIndexRoute: typeof EmployeeReportsIndexRoute
>>>>>>> janani/main
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeProgramsRoute: EmployeeProgramsRoute,
<<<<<<< HEAD
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
=======
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeReportsReportIdRoute: EmployeeReportsReportIdRoute,
  EmployeeReportsIndexRoute: EmployeeReportsIndexRoute,
>>>>>>> janani/main
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppReportsNewRoute: typeof AppReportsNewRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppReportsNewRoute: AppReportsNewRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppEmployeeRoute: typeof AppEmployeeRoute
  AppManagerRoute: typeof AppManagerRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppProgramsRoute: typeof AppProgramsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppResearcherRoute: typeof AppResearcherRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppEmployeeRoute: AppEmployeeRoute,
  AppManagerRoute: AppManagerRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppProgramsRoute: AppProgramsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppResearcherRoute: AppResearcherRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WaitingApprovalRoute: WaitingApprovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
